version: '3'
services:
  phillydb:
    build: .
    image: phillydb
    entrypoint: phillydb
    volumes:
      - .:/app
  python:
    image: phillydb
    entrypoint: |
      python
    volumes:
      - .:/app
    depends_on:
      - phillydb

  test:
    image: phillydb
    entrypoint: py.test -n0
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  jupyter:
    image: phillydb
    ports:
      - "${HOST_PORT_JUPYTER:-8888}:${HOST_PORT_JUPYTER:-8888}"
    entrypoint: |
      jupyter notebook notebooks/ --ip=0.0.0.0 --port=${HOST_PORT_JUPYTER:-8888} --allow-root --no-browser
    volumes:
      - .:/app
